spring.application.name=liveSignalMap

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/signalmap}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345678}

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized?